stages:
- test
- docker_build

test:
  image: "python:2.7"
  stage: test
  script:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - PYTHONPATH=. py.test --verbose -s

docker_build:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
  - docker_build -t myapp .
